DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ACCOUNT;
 
CREATE TABLE ACCOUNT (
  ACCOUNT_ID INT AUTO_INCREMENT  PRIMARY KEY,
  ACCOUNT_HOLDER VARCHAR(250) NOT NULL,
  BALANCE NUMBER(10,2) NOT NULL,
);
 
CREATE TABLE TRANSACTION (
  TRANSACTION_ID INT AUTO_INCREMENT  PRIMARY KEY,
  ACCOUNT_ID INT NOT NULL,
  TRANSACTION_TYPE VARCHAR2(10) NOT NULL,
  AMOUNT NUMBER(10,2) NOT NULL,
  TRANSACTION_DATE DATE
);

CREATE SEQUENCE TRANSACTION_SEQ;
  INSERT INTO ACCOUNT (account_id, ACCOUNT_HOLDER, BALANCE) VALUES
  (111, 'Miss Marple' ,1000.00),
  (222, 'Sherlock Holmes', 200.00),
  (333, 'Hercule Poirot',300.00);
  
  
  
  
	